name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rust-stable:
    name: Rust Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: make build-rust
      - run: make lint-rust
      - run: make doc-rust
      - run: make test-rust

  rust-msrv:
    name: Rust MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
      - run: make build-rust
      - run: make test-rust

  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: make test-python
